// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file sampleData.hpp
 * This header file contains the declaration of the described types in the IDL file.
 *
 * This file was generated by the tool fastddsgen.
 */

#ifndef FAST_DDS_GENERATED__SAMPLEDATA_IDL_SAMPLEDATA_HPP
#define FAST_DDS_GENERATED__SAMPLEDATA_IDL_SAMPLEDATA_HPP

#include <cstdint>
#include <string>
#include <utility>
#include <fastcdr/cdr/fixed_size_string.hpp>

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#define eProsima_user_DllExport __declspec( dllexport )
#else
#define eProsima_user_DllExport
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define eProsima_user_DllExport
#endif  // _WIN32

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#if defined(SAMPLEDATA_SOURCE)
#define SAMPLEDATA_DllAPI __declspec( dllexport )
#else
#define SAMPLEDATA_DllAPI __declspec( dllimport )
#endif // SAMPLEDATA_SOURCE
#else
#define SAMPLEDATA_DllAPI
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define SAMPLEDATA_DllAPI
#endif // _WIN32

namespace sampleData_idl {

typedef int32_t Level;

/*!
 * @brief This class represents the structure Vec3Df defined by the user in the IDL file.
 * @ingroup sampleData
 */
class Vec3Df
{
public:

    /*!
     * @brief Default constructor.
     */
    eProsima_user_DllExport Vec3Df()
    {
    }

    /*!
     * @brief Default destructor.
     */
    eProsima_user_DllExport ~Vec3Df()
    {
    }

    /*!
     * @brief Copy constructor.
     * @param x Reference to the object Vec3Df that will be copied.
     */
    eProsima_user_DllExport Vec3Df(
            const Vec3Df& x)
    {
                    m_x = x.m_x;

                    m_y = x.m_y;

                    m_z = x.m_z;

    }

    /*!
     * @brief Move constructor.
     * @param x Reference to the object Vec3Df that will be copied.
     */
    eProsima_user_DllExport Vec3Df(
            Vec3Df&& x) noexcept
    {
        m_x = x.m_x;
        m_y = x.m_y;
        m_z = x.m_z;
    }

    /*!
     * @brief Copy assignment.
     * @param x Reference to the object Vec3Df that will be copied.
     */
    eProsima_user_DllExport Vec3Df& operator =(
            const Vec3Df& x)
    {

                    m_x = x.m_x;

                    m_y = x.m_y;

                    m_z = x.m_z;

        return *this;
    }

    /*!
     * @brief Move assignment.
     * @param x Reference to the object Vec3Df that will be copied.
     */
    eProsima_user_DllExport Vec3Df& operator =(
            Vec3Df&& x) noexcept
    {

        m_x = x.m_x;
        m_y = x.m_y;
        m_z = x.m_z;
        return *this;
    }

    /*!
     * @brief Comparison operator.
     * @param x Vec3Df object to compare.
     */
    eProsima_user_DllExport bool operator ==(
            const Vec3Df& x) const
    {
        return (m_x == x.m_x &&
           m_y == x.m_y &&
           m_z == x.m_z);
    }

    /*!
     * @brief Comparison operator.
     * @param x Vec3Df object to compare.
     */
    eProsima_user_DllExport bool operator !=(
            const Vec3Df& x) const
    {
        return !(*this == x);
    }

    /*!
     * @brief This function sets a value in member x
     * @param _x New value for member x
     */
    eProsima_user_DllExport void x(
            double _x)
    {
        m_x = _x;
    }

    /*!
     * @brief This function returns the value of member x
     * @return Value of member x
     */
    eProsima_user_DllExport double x() const
    {
        return m_x;
    }

    /*!
     * @brief This function returns a reference to member x
     * @return Reference to member x
     */
    eProsima_user_DllExport double& x()
    {
        return m_x;
    }


    /*!
     * @brief This function sets a value in member y
     * @param _y New value for member y
     */
    eProsima_user_DllExport void y(
            double _y)
    {
        m_y = _y;
    }

    /*!
     * @brief This function returns the value of member y
     * @return Value of member y
     */
    eProsima_user_DllExport double y() const
    {
        return m_y;
    }

    /*!
     * @brief This function returns a reference to member y
     * @return Reference to member y
     */
    eProsima_user_DllExport double& y()
    {
        return m_y;
    }


    /*!
     * @brief This function sets a value in member z
     * @param _z New value for member z
     */
    eProsima_user_DllExport void z(
            double _z)
    {
        m_z = _z;
    }

    /*!
     * @brief This function returns the value of member z
     * @return Value of member z
     */
    eProsima_user_DllExport double z() const
    {
        return m_z;
    }

    /*!
     * @brief This function returns a reference to member z
     * @return Reference to member z
     */
    eProsima_user_DllExport double& z()
    {
        return m_z;
    }



private:

    double m_x{0.0};
    double m_y{0.0};
    double m_z{0.0};

};
/*!
 * @brief This class represents the structure EntityData defined by the user in the IDL file.
 * @ingroup sampleData
 */
class EntityData
{
public:

    /*!
     * @brief Default constructor.
     */
    eProsima_user_DllExport EntityData()
    {
    }

    /*!
     * @brief Default destructor.
     */
    eProsima_user_DllExport ~EntityData()
    {
    }

    /*!
     * @brief Copy constructor.
     * @param x Reference to the object EntityData that will be copied.
     */
    eProsima_user_DllExport EntityData(
            const EntityData& x)
    {
                    m_time = x.m_time;

                    m_entityId = x.m_entityId;

                    m_pos = x.m_pos;

                    m_entityLevel = x.m_entityLevel;

    }

    /*!
     * @brief Move constructor.
     * @param x Reference to the object EntityData that will be copied.
     */
    eProsima_user_DllExport EntityData(
            EntityData&& x) noexcept
    {
        m_time = std::move(x.m_time);
        m_entityId = std::move(x.m_entityId);
        m_pos = std::move(x.m_pos);
        m_entityLevel = x.m_entityLevel;
    }

    /*!
     * @brief Copy assignment.
     * @param x Reference to the object EntityData that will be copied.
     */
    eProsima_user_DllExport EntityData& operator =(
            const EntityData& x)
    {

                    m_time = x.m_time;

                    m_entityId = x.m_entityId;

                    m_pos = x.m_pos;

                    m_entityLevel = x.m_entityLevel;

        return *this;
    }

    /*!
     * @brief Move assignment.
     * @param x Reference to the object EntityData that will be copied.
     */
    eProsima_user_DllExport EntityData& operator =(
            EntityData&& x) noexcept
    {

        m_time = std::move(x.m_time);
        m_entityId = std::move(x.m_entityId);
        m_pos = std::move(x.m_pos);
        m_entityLevel = x.m_entityLevel;
        return *this;
    }

    /*!
     * @brief Comparison operator.
     * @param x EntityData object to compare.
     */
    eProsima_user_DllExport bool operator ==(
            const EntityData& x) const
    {
        return (m_time == x.m_time &&
           m_entityId == x.m_entityId &&
           m_pos == x.m_pos &&
           m_entityLevel == x.m_entityLevel);
    }

    /*!
     * @brief Comparison operator.
     * @param x EntityData object to compare.
     */
    eProsima_user_DllExport bool operator !=(
            const EntityData& x) const
    {
        return !(*this == x);
    }

    /*!
     * @brief This function copies the value in member time
     * @param _time New value to be copied in member time
     */
    eProsima_user_DllExport void time(
            const std::string& _time)
    {
        m_time = _time;
    }

    /*!
     * @brief This function moves the value in member time
     * @param _time New value to be moved in member time
     */
    eProsima_user_DllExport void time(
            std::string&& _time)
    {
        m_time = std::move(_time);
    }

    /*!
     * @brief This function returns a constant reference to member time
     * @return Constant reference to member time
     */
    eProsima_user_DllExport const std::string& time() const
    {
        return m_time;
    }

    /*!
     * @brief This function returns a reference to member time
     * @return Reference to member time
     */
    eProsima_user_DllExport std::string& time()
    {
        return m_time;
    }


    /*!
     * @brief This function copies the value in member entityId
     * @param _entityId New value to be copied in member entityId
     */
    eProsima_user_DllExport void entityId(
            const std::string& _entityId)
    {
        m_entityId = _entityId;
    }

    /*!
     * @brief This function moves the value in member entityId
     * @param _entityId New value to be moved in member entityId
     */
    eProsima_user_DllExport void entityId(
            std::string&& _entityId)
    {
        m_entityId = std::move(_entityId);
    }

    /*!
     * @brief This function returns a constant reference to member entityId
     * @return Constant reference to member entityId
     */
    eProsima_user_DllExport const std::string& entityId() const
    {
        return m_entityId;
    }

    /*!
     * @brief This function returns a reference to member entityId
     * @return Reference to member entityId
     */
    eProsima_user_DllExport std::string& entityId()
    {
        return m_entityId;
    }


    /*!
     * @brief This function copies the value in member pos
     * @param _pos New value to be copied in member pos
     */
    eProsima_user_DllExport void pos(
            const Vec3Df& _pos)
    {
        m_pos = _pos;
    }

    /*!
     * @brief This function moves the value in member pos
     * @param _pos New value to be moved in member pos
     */
    eProsima_user_DllExport void pos(
            Vec3Df&& _pos)
    {
        m_pos = std::move(_pos);
    }

    /*!
     * @brief This function returns a constant reference to member pos
     * @return Constant reference to member pos
     */
    eProsima_user_DllExport const Vec3Df& pos() const
    {
        return m_pos;
    }

    /*!
     * @brief This function returns a reference to member pos
     * @return Reference to member pos
     */
    eProsima_user_DllExport Vec3Df& pos()
    {
        return m_pos;
    }


    /*!
     * @brief This function sets a value in member entityLevel
     * @param _entityLevel New value for member entityLevel
     */
    eProsima_user_DllExport void entityLevel(
            Level _entityLevel)
    {
        m_entityLevel = _entityLevel;
    }

    /*!
     * @brief This function returns the value of member entityLevel
     * @return Value of member entityLevel
     */
    eProsima_user_DllExport Level entityLevel() const
    {
        return m_entityLevel;
    }

    /*!
     * @brief This function returns a reference to member entityLevel
     * @return Reference to member entityLevel
     */
    eProsima_user_DllExport Level& entityLevel()
    {
        return m_entityLevel;
    }



private:

    std::string m_time;
    std::string m_entityId;
    Vec3Df m_pos;
    Level m_entityLevel{0};

};

} // namespace sampleData_idl

#endif // _FAST_DDS_GENERATED_SAMPLEDATA_IDL_SAMPLEDATA_HPP_


