// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file sampleDataTypeObjectSupport.cxx
 * Source file containing the implementation to register the TypeObject representation of the described types in the IDL file
 *
 * This file was generated by the tool fastddsgen.
 */

#include "sampleDataTypeObjectSupport.hpp"

#include <mutex>
#include <string>

#include <fastcdr/xcdr/external.hpp>
#include <fastcdr/xcdr/optional.hpp>
#include <fastdds/dds/domain/DomainParticipantFactory.hpp>
#include <fastdds/dds/log/Log.hpp>
#include <fastdds/dds/xtypes/common.hpp>
#include <fastdds/dds/xtypes/type_representation/ITypeObjectRegistry.hpp>
#include <fastdds/dds/xtypes/type_representation/TypeObject.hpp>
#include <fastdds/dds/xtypes/type_representation/TypeObjectUtils.hpp>

#include "sampleData.hpp"


using namespace eprosima::fastdds::dds::xtypes;

namespace sampleData_idl {
void register_Level_type_identifier(
        TypeIdentifierPair& type_ids_Level)
{
    ReturnCode_t return_code_Level {eprosima::fastdds::dds::RETCODE_OK};
    return_code_Level =
        eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
        "sampleData_idl::Level", type_ids_Level);
    if (eprosima::fastdds::dds::RETCODE_OK != return_code_Level)
    {
        AliasTypeFlag alias_flags_Level = 0;
        QualifiedTypeName type_name_Level = "sampleData_idl::Level";
        eprosima::fastcdr::optional<AppliedBuiltinTypeAnnotations> type_ann_builtin_Level;
        eprosima::fastcdr::optional<AppliedAnnotationSeq> ann_custom_Level;
        CompleteTypeDetail detail_Level = TypeObjectUtils::build_complete_type_detail(type_ann_builtin_Level, ann_custom_Level, type_name_Level.to_string());
        CompleteAliasHeader header_Level = TypeObjectUtils::build_complete_alias_header(detail_Level);
        AliasMemberFlag related_flags_Level = 0;
        return_code_Level =
            eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
            "_int32_t", type_ids_Level);

        if (eprosima::fastdds::dds::RETCODE_OK != return_code_Level)
        {
            EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                    "sampleData_idl::Level related TypeIdentifier unknown to TypeObjectRegistry.");
            return;
        }
        bool common_Level_ec {false};
        CommonAliasBody common_Level {TypeObjectUtils::build_common_alias_body(related_flags_Level,
                TypeObjectUtils::retrieve_complete_type_identifier(type_ids_Level, common_Level_ec))};
        if (!common_Level_ec)
        {
            EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "sampleData_idl::Level related TypeIdentifier inconsistent.");
            return;
        }
        eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_Level;
        ann_custom_Level.reset();
        CompleteAliasBody body_Level = TypeObjectUtils::build_complete_alias_body(common_Level,
                member_ann_builtin_Level, ann_custom_Level);
        CompleteAliasType alias_type_Level = TypeObjectUtils::build_complete_alias_type(alias_flags_Level,
                header_Level, body_Level);
        if (eprosima::fastdds::dds::RETCODE_BAD_PARAMETER ==
                TypeObjectUtils::build_and_register_alias_type_object(alias_type_Level,
                    type_name_Level.to_string(), type_ids_Level))
        {
            EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                "sampleData_idl::Level already registered in TypeObjectRegistry for a different type.");
        }
    }
}

// TypeIdentifier is returned by reference: dependent structures/unions are registered in this same method
void register_Vec3Df_type_identifier(
        TypeIdentifierPair& type_ids_Vec3Df)
{

    ReturnCode_t return_code_Vec3Df {eprosima::fastdds::dds::RETCODE_OK};
    return_code_Vec3Df =
        eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
        "sampleData_idl::Vec3Df", type_ids_Vec3Df);
    if (eprosima::fastdds::dds::RETCODE_OK != return_code_Vec3Df)
    {
        StructTypeFlag struct_flags_Vec3Df = TypeObjectUtils::build_struct_type_flag(eprosima::fastdds::dds::xtypes::ExtensibilityKind::APPENDABLE,
                false, false);
        QualifiedTypeName type_name_Vec3Df = "sampleData_idl::Vec3Df";
        eprosima::fastcdr::optional<AppliedBuiltinTypeAnnotations> type_ann_builtin_Vec3Df;
        eprosima::fastcdr::optional<AppliedAnnotationSeq> ann_custom_Vec3Df;
        CompleteTypeDetail detail_Vec3Df = TypeObjectUtils::build_complete_type_detail(type_ann_builtin_Vec3Df, ann_custom_Vec3Df, type_name_Vec3Df.to_string());
        CompleteStructHeader header_Vec3Df;
        header_Vec3Df = TypeObjectUtils::build_complete_struct_header(TypeIdentifier(), detail_Vec3Df);
        CompleteStructMemberSeq member_seq_Vec3Df;
        {
            TypeIdentifierPair type_ids_x;
            ReturnCode_t return_code_x {eprosima::fastdds::dds::RETCODE_OK};
            return_code_x =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "_double", type_ids_x);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_x)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                        "x Structure member TypeIdentifier unknown to TypeObjectRegistry.");
                return;
            }
            StructMemberFlag member_flags_x = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_x = 0x00000000;
            bool common_x_ec {false};
            CommonStructMember common_x {TypeObjectUtils::build_common_struct_member(member_id_x, member_flags_x, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_x, common_x_ec))};
            if (!common_x_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure x member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_x = "x";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_x;
            ann_custom_Vec3Df.reset();
            CompleteMemberDetail detail_x = TypeObjectUtils::build_complete_member_detail(name_x, member_ann_builtin_x, ann_custom_Vec3Df);
            CompleteStructMember member_x = TypeObjectUtils::build_complete_struct_member(common_x, detail_x);
            TypeObjectUtils::add_complete_struct_member(member_seq_Vec3Df, member_x);
        }
        {
            TypeIdentifierPair type_ids_y;
            ReturnCode_t return_code_y {eprosima::fastdds::dds::RETCODE_OK};
            return_code_y =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "_double", type_ids_y);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_y)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                        "y Structure member TypeIdentifier unknown to TypeObjectRegistry.");
                return;
            }
            StructMemberFlag member_flags_y = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_y = 0x00000001;
            bool common_y_ec {false};
            CommonStructMember common_y {TypeObjectUtils::build_common_struct_member(member_id_y, member_flags_y, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_y, common_y_ec))};
            if (!common_y_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure y member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_y = "y";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_y;
            ann_custom_Vec3Df.reset();
            CompleteMemberDetail detail_y = TypeObjectUtils::build_complete_member_detail(name_y, member_ann_builtin_y, ann_custom_Vec3Df);
            CompleteStructMember member_y = TypeObjectUtils::build_complete_struct_member(common_y, detail_y);
            TypeObjectUtils::add_complete_struct_member(member_seq_Vec3Df, member_y);
        }
        {
            TypeIdentifierPair type_ids_z;
            ReturnCode_t return_code_z {eprosima::fastdds::dds::RETCODE_OK};
            return_code_z =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "_double", type_ids_z);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_z)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                        "z Structure member TypeIdentifier unknown to TypeObjectRegistry.");
                return;
            }
            StructMemberFlag member_flags_z = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_z = 0x00000002;
            bool common_z_ec {false};
            CommonStructMember common_z {TypeObjectUtils::build_common_struct_member(member_id_z, member_flags_z, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_z, common_z_ec))};
            if (!common_z_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure z member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_z = "z";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_z;
            ann_custom_Vec3Df.reset();
            CompleteMemberDetail detail_z = TypeObjectUtils::build_complete_member_detail(name_z, member_ann_builtin_z, ann_custom_Vec3Df);
            CompleteStructMember member_z = TypeObjectUtils::build_complete_struct_member(common_z, detail_z);
            TypeObjectUtils::add_complete_struct_member(member_seq_Vec3Df, member_z);
        }
        CompleteStructType struct_type_Vec3Df = TypeObjectUtils::build_complete_struct_type(struct_flags_Vec3Df, header_Vec3Df, member_seq_Vec3Df);
        if (eprosima::fastdds::dds::RETCODE_BAD_PARAMETER ==
                TypeObjectUtils::build_and_register_struct_type_object(struct_type_Vec3Df, type_name_Vec3Df.to_string(), type_ids_Vec3Df))
        {
            EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                    "sampleData_idl::Vec3Df already registered in TypeObjectRegistry for a different type.");
        }
    }
}
// TypeIdentifier is returned by reference: dependent structures/unions are registered in this same method
void register_EntityData_type_identifier(
        TypeIdentifierPair& type_ids_EntityData)
{

    ReturnCode_t return_code_EntityData {eprosima::fastdds::dds::RETCODE_OK};
    return_code_EntityData =
        eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
        "sampleData_idl::EntityData", type_ids_EntityData);
    if (eprosima::fastdds::dds::RETCODE_OK != return_code_EntityData)
    {
        StructTypeFlag struct_flags_EntityData = TypeObjectUtils::build_struct_type_flag(eprosima::fastdds::dds::xtypes::ExtensibilityKind::APPENDABLE,
                false, false);
        QualifiedTypeName type_name_EntityData = "sampleData_idl::EntityData";
        eprosima::fastcdr::optional<AppliedBuiltinTypeAnnotations> type_ann_builtin_EntityData;
        eprosima::fastcdr::optional<AppliedAnnotationSeq> ann_custom_EntityData;
        CompleteTypeDetail detail_EntityData = TypeObjectUtils::build_complete_type_detail(type_ann_builtin_EntityData, ann_custom_EntityData, type_name_EntityData.to_string());
        CompleteStructHeader header_EntityData;
        header_EntityData = TypeObjectUtils::build_complete_struct_header(TypeIdentifier(), detail_EntityData);
        CompleteStructMemberSeq member_seq_EntityData;
        {
            TypeIdentifierPair type_ids_time;
            ReturnCode_t return_code_time {eprosima::fastdds::dds::RETCODE_OK};
            return_code_time =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "anonymous_string_unbounded", type_ids_time);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_time)
            {
                {
                    SBound bound = 0;
                    StringSTypeDefn string_sdefn = TypeObjectUtils::build_string_s_type_defn(bound);
                    if (eprosima::fastdds::dds::RETCODE_BAD_PARAMETER ==
                            TypeObjectUtils::build_and_register_s_string_type_identifier(string_sdefn,
                            "anonymous_string_unbounded", type_ids_time))
                    {
                        EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                            "anonymous_string_unbounded already registered in TypeObjectRegistry for a different type.");
                    }
                }
            }
            StructMemberFlag member_flags_time = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_time = 0x00000000;
            bool common_time_ec {false};
            CommonStructMember common_time {TypeObjectUtils::build_common_struct_member(member_id_time, member_flags_time, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_time, common_time_ec))};
            if (!common_time_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure time member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_time = "time";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_time;
            ann_custom_EntityData.reset();
            CompleteMemberDetail detail_time = TypeObjectUtils::build_complete_member_detail(name_time, member_ann_builtin_time, ann_custom_EntityData);
            CompleteStructMember member_time = TypeObjectUtils::build_complete_struct_member(common_time, detail_time);
            TypeObjectUtils::add_complete_struct_member(member_seq_EntityData, member_time);
        }
        {
            TypeIdentifierPair type_ids_entityId;
            ReturnCode_t return_code_entityId {eprosima::fastdds::dds::RETCODE_OK};
            return_code_entityId =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "anonymous_string_unbounded", type_ids_entityId);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_entityId)
            {
                {
                    SBound bound = 0;
                    StringSTypeDefn string_sdefn = TypeObjectUtils::build_string_s_type_defn(bound);
                    if (eprosima::fastdds::dds::RETCODE_BAD_PARAMETER ==
                            TypeObjectUtils::build_and_register_s_string_type_identifier(string_sdefn,
                            "anonymous_string_unbounded", type_ids_entityId))
                    {
                        EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                            "anonymous_string_unbounded already registered in TypeObjectRegistry for a different type.");
                    }
                }
            }
            StructMemberFlag member_flags_entityId = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_entityId = 0x00000001;
            bool common_entityId_ec {false};
            CommonStructMember common_entityId {TypeObjectUtils::build_common_struct_member(member_id_entityId, member_flags_entityId, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_entityId, common_entityId_ec))};
            if (!common_entityId_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure entityId member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_entityId = "entityId";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_entityId;
            ann_custom_EntityData.reset();
            CompleteMemberDetail detail_entityId = TypeObjectUtils::build_complete_member_detail(name_entityId, member_ann_builtin_entityId, ann_custom_EntityData);
            CompleteStructMember member_entityId = TypeObjectUtils::build_complete_struct_member(common_entityId, detail_entityId);
            TypeObjectUtils::add_complete_struct_member(member_seq_EntityData, member_entityId);
        }
        {
            TypeIdentifierPair type_ids_pos;
            ReturnCode_t return_code_pos {eprosima::fastdds::dds::RETCODE_OK};
            return_code_pos =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "sampleData_idl::Vec3Df", type_ids_pos);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_pos)
            {
                sampleData_idl::register_Vec3Df_type_identifier(type_ids_pos);
            }
            StructMemberFlag member_flags_pos = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_pos = 0x00000002;
            bool common_pos_ec {false};
            CommonStructMember common_pos {TypeObjectUtils::build_common_struct_member(member_id_pos, member_flags_pos, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_pos, common_pos_ec))};
            if (!common_pos_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure pos member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_pos = "pos";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_pos;
            ann_custom_EntityData.reset();
            CompleteMemberDetail detail_pos = TypeObjectUtils::build_complete_member_detail(name_pos, member_ann_builtin_pos, ann_custom_EntityData);
            CompleteStructMember member_pos = TypeObjectUtils::build_complete_struct_member(common_pos, detail_pos);
            TypeObjectUtils::add_complete_struct_member(member_seq_EntityData, member_pos);
        }
        {
            TypeIdentifierPair type_ids_entityLevel;
            ReturnCode_t return_code_entityLevel {eprosima::fastdds::dds::RETCODE_OK};
            return_code_entityLevel =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "sampleData_idl::Level", type_ids_entityLevel);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_entityLevel)
            {
                sampleData_idl::register_Level_type_identifier(type_ids_entityLevel);
            }
            StructMemberFlag member_flags_entityLevel = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_entityLevel = 0x00000003;
            bool common_entityLevel_ec {false};
            CommonStructMember common_entityLevel {TypeObjectUtils::build_common_struct_member(member_id_entityLevel, member_flags_entityLevel, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_entityLevel, common_entityLevel_ec))};
            if (!common_entityLevel_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure entityLevel member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_entityLevel = "entityLevel";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_entityLevel;
            ann_custom_EntityData.reset();
            CompleteMemberDetail detail_entityLevel = TypeObjectUtils::build_complete_member_detail(name_entityLevel, member_ann_builtin_entityLevel, ann_custom_EntityData);
            CompleteStructMember member_entityLevel = TypeObjectUtils::build_complete_struct_member(common_entityLevel, detail_entityLevel);
            TypeObjectUtils::add_complete_struct_member(member_seq_EntityData, member_entityLevel);
        }
        CompleteStructType struct_type_EntityData = TypeObjectUtils::build_complete_struct_type(struct_flags_EntityData, header_EntityData, member_seq_EntityData);
        if (eprosima::fastdds::dds::RETCODE_BAD_PARAMETER ==
                TypeObjectUtils::build_and_register_struct_type_object(struct_type_EntityData, type_name_EntityData.to_string(), type_ids_EntityData))
        {
            EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                    "sampleData_idl::EntityData already registered in TypeObjectRegistry for a different type.");
        }
    }
}

} // namespace sampleData_idl

